---
title: "WICHE R Package"
author: "Matt Campbell"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction

`wicher` is a package used to make working with the WICHE enrollment
projections easier in R. We generally use WICHE enrollments to figure
out participation rates for us states. You can also use WICHE to visualize
demographics.

## WICHE Datasets



```{r warning = FALSE, message = FALSE, echo = TRUE}

library(wicher)

enrollments <- lookup_wiche(year = 2012:2016, gender = c("f", "m"))

```

`r knitr::kable(enrollments)` 

```{r warning = FALSE, message = FALSE, echo = TRUE}

library(ggplot2)

enrollments <- lookup_wiche(year = 2006:2026, gender = c("f", "m"))

qplot(year, n, data = enrollments, 
      color = gender, 
      geom = c("point", "smooth"),
      main = "WICHE Projections",
      xlab = "Academic Year", 
      ylab = "Projection")

```      

